Add my custom overlayfs code for init and livekitlib scripts.

diff --git a/livekitlib b/livekitlib
--- a/livekitlib
+++ b/livekitlib
@@ -25,8 +25,21 @@ get_exclude()
     done
 }
 
+get_lowerdirs()
+{
+	local BUND_DIRS BUND_EXT BUND
+	BUND_DIRS="$1"
+	BUND_EXT="$2"
+	MNT_OPT=""
+
+	MNT_OPT="$(find "$BUND_DIRS" -maxdepth 1 -type d -name "*.${BUND_EXT}" | \
+        sort | while read BUND; do echo -n "${BUND}:"; done)"
+	    MNT_OPT="${MNT_OPT%?}"
+	    echo "$MNT_OPT"
+}
+
 # NOTE: DO NOT TOUCH THE ESCAPE CHARACTERS!
-BLUE="[1;34m"
+CYAN="[1;36m"
 YELLOW="[1;33m"
 ORANGE="[0;33m"
 GREEN="[1;32m"
@@ -67,7 +80,7 @@ debug_log()
 # $1 = text to show
 echo_fatal()
 {
-    echo "[${RED}"' fatal '"${NC}] $@" >&2
+    echo "<${RED}"'fatal'"${NC}> $*" >&2
 }
 
 # echo bold
@@ -75,36 +88,36 @@ echo_fatal()
 #
 echo_bold()
 {
-    echo "$BOLD""$@""$NC"
+    echo "$BOLD""$*""$NC"
 }
 
 # echo livekit tag
 echo_livekit()
 {
-    echo "[${BLUE}"'livekit'"${NC}] "
+    echo -n "<${CYAN}"'llkim'"${NC}> "
 }
 
 echo_livekit_msg()
 {
-    echo "[${BLUE}"'livekit'"${NC}] $@"
+    echo "<${CYAN}"'llkim'"${NC}> $*"
 }
 
 # echo error
 echo_err()
 {
-    echo "[${RED}"' error '"${NC}] $@" >&2
+    echo "<${RED}"'error'"${NC}> $*" >&2
 }
 
 # echo warn
 echo_warn()
 {
-    echo "[${YELLOW}"' warn! '"${NC}] $@" >&2
+    echo "<${YELLOW}"'warn!'"${NC}> $*" >&2
 }
 
 # echo signature
 echo_sign()
 {
-    echo "${BOLD}"' Linux Live Kit Improved v1.0 - '"$* ${NC}"
+    echo_bold " Live Kit Improved v1.0 (Experimental, OverlayFS) - $*" >&2
 }
 
 # log - store given text in /var/log/livedbg
@@ -123,8 +136,8 @@ echolog()
 show_debug_banner()
 {
    echo_sign "DEBUGGING MODE"
-   echo "The root shell is prepared for you!" >&2
-   echo "Type your desired commands or press Ctrl-D to continue booting." >&2
+   echo "Here's the root shell for you..." >&2
+   echo "Type your desired commands or hit Ctrl+D to continue bootup..." >&2
    echo >&2
 }
 
@@ -202,8 +215,7 @@ cmdline_value()
 transfer_initramfs()
 {
    if [ ! -r /lib/esc_initramfs.sgn ]; then
-      echo_livekit >&2
-      echo "Switching root from initramfs to tmpfs..." >&2
+      echo_livekit_msg "Switching root from initramfs to tmpfs..." >&2
       SWITCH=/m # one letter directory
       mkdir -p $SWITCH
       mount -t tmpfs -o size="100%" tmpfs "$SWITCH"
@@ -231,22 +243,22 @@ init_proc_sysfs()
 # modprobe all modules found in initial ramdisk
 modprobe_everything()
 {
-   debug_log "modprobe_everything" "$*"
+    debug_log "modprobe_everything" "$*"
 
-   echo_livekit_msg "Probing for hardware..." >&2
+    echo_livekit_msg "Probing for hardware..." >&2
 
-   find /lib/modules/ | fgrep '.ko' | xargs -n 1 modprobe 2>/dev/null
-   refresh_devs
+    find /lib/modules/ | fgrep '.ko' | xargs -n 1 modprobe 2>/dev/null
+    refresh_devs
 }
 
 
 refresh_devs()
 {
-   debug_log "refresh_devs" "$*"
-   if [ -r /proc/sys/kernel/hotplug ]; then
-      echo /sbin/mdev > /proc/sys/kernel/hotplug
-   fi
-   mdev -s
+    debug_log "refresh_devs" "$*"
+    if [ -r /proc/sys/kernel/hotplug ]; then
+        echo /sbin/mdev > /proc/sys/kernel/hotplug
+    fi
+    mdev -s
 }
 
 # make sure some devices are there
@@ -276,47 +288,24 @@ init_zram()
     fi
 }
 
-# load the AUFS kernel module if needed
+# Load OverlayFS kernel module
 #
-init_aufs()
+modprobe_overlay()
 {
-    debug_log "init_aufs" "$*"
+    debug_log "modprobe_overlay" "$*"
 
     # Prepare for error messages
     echo >>/var/log/livkekit-log
 
-    modprobe aufs 2>/var/log/livekit-log
+    modprobe overlay 2>>/var/log/livekit-log
 
-    # If aufs module failed to load, panic immidiately
+    # If overlay module failed to load, panic immidiately
     if [ $? -ne 0 ]; then
-        fatal "Failed to load AUFS module!"
+        fatal "Failed to load OverlayFS module!"
     fi
 
     # finally, refresh all devices
     refresh_devs
-}
-
-# Setup empty union
-# $1 = changes directory (ramfs or persistent changes)
-# $2 = union directory where to mount the union
-#
-init_union()
-{
-   debug_log "init_union" "$*"
-
-   echo_livekit_msg "Initialising AUFS union..."
-   mkdir -p "$1"
-   mkdir -p "$2"
-
-   # Prepare for error messages
-   echo >>/var/log/livekit-log
-
-   mount -t aufs -o xino="/.xino",trunc_xino,br="$1" aufs "$2" >/var/log/livekit-log 2>&1
-
-   # If failed to init union, panic
-   if [ $? -ne 0 ]; then
-       fatal "Failed to initialise AUFS union!"
-   fi
 }
 
 # Return device mounted for given directory
@@ -583,6 +572,7 @@ persistent_changes()
 
     # If persistent changes are not requested, end here
     if grep -vq 'perch' /proc/cmdline; then
+        NOCHANGE="yes"
         return
     fi
 
@@ -700,31 +690,84 @@ sortmod()
 # and add them to union
 # $1 = directory where to search for bundles
 # $2 = directory where to mount bundles
-# $3 = directory where union is mounted
-#
-union_append_bundles()
+# $3 = modpath option to add more modules (optional)
+mount_append_bundles()
 {
-    debug_log "union_append_bundles" "$*"
+    debug_log "mount_append_bundles" "$*"
 
-    local BUN
+    local BUN modpath
+    
+    if [ "$3" == "" ]; then
+        modpath="modules"
+    else
+		modpath="$3"
+	fi
 
     echo_livekit >&2
-    echo "Appending bundles to union..." >&2
+    echo "Appending bundles for union setup..." >&2
 
     # Just tell me why! Why be compact?!?
-    ( ls -1 "$1" | sort -n ; cd "$1" ; find modules/ 2>/dev/null | \
+    ( ls -1 "$1" | sort -n ; cd "$1" ; find "$modpath"/ 2>/dev/null | \
     sortmod | filter_load) | grep '[.]'$BEXT'$' |\
     filter_noload | \
     while read BUNDLE; do
-        echo_livekit_msg "Appending: $BUNDLE" >&2
-
         BUN="$(basename "$BUNDLE")"
+        echo_livekit_msg "Mounting $BUN to $BUNDLES ..." >&2
         mkdir -p "$2/$BUN"
 
         # It now depends on your kernel!
         mount -o loop -t squashfs "$1/$BUNDLE" "$2/$BUN"
-        mount -o remount,add:1:"$2/$BUN" aufs "$3"
     done
+}
+
+# Mount squashfs filesystem bundles
+# and add them to union
+# NEW: Prepare Overlay file system
+# $1 = directory where to search for bundles
+# $2 = directory where to mount bundles
+# $3 = directory where the changes is
+# $4 = directory where union is supposed to be
+#
+prepare_overlay()
+{
+    debug_log "prepare_overlay" "$*"
+
+    local BUN ALL_BUNDS LOWERDIR UPPERDIR WORKDIR
+
+    mount_append_bundles "$1" "$2"
+	MODPATH="$(cmdline_value modpath)"
+	if [ "$MODPATH" != "" ]; then
+		mount_append_bundles "$DATAMNT" "$2" "$MODPATH"
+	fi
+
+    ALL_BUNDS="$(get_lowerdirs "$2" "$BEXT")"
+    LOWERDIR="$MEMORY/lowerdir"
+    UPPERDIR="$3"
+    WORKDIR="$MEMORY/work"
+
+    # Make the workdir (cuz it's non-existant, yet...)
+    mkdir "$WORKDIR" >/dev/null 2>&1
+
+    # Make the union directory (this might actually be an alarming bug)
+    mkdir "$4" >/dev/null 2>&1
+    
+    if [ "$NOCHANGE" == "" ]; then
+        WORKDIR=$DATA/work
+        UPPERDIR=$DATA/changes
+    fi
+    # I think this is a work-around
+    # Separating 2 commands to avoid overflow (aka avoid triggering "Argument list to long" error)
+    mkdir "$LOWERDIR" >/dev/null 2>&1
+    mount -t overlay -o lowerdir="$ALL_BUNDS" overlay "$LOWERDIR" >>/var/log/livekit-log 2>&1 && \
+    mount -t overlay -o lowerdir="$LOWERDIR",upperdir="$UPPERDIR",workdir="$WORKDIR" \
+    overlay "$4" >>/var/log/livekit-log 2>&1
+
+    # Check if we got any errors...
+    if [ $? -ne 0 ]; then
+    	fatal "Failed to prepare OverlayFS union!"
+    else
+    	echo_livekit_msg "And we have lift-off!" >&2
+    fi
 }
 
 # Create empty fstab properly
@@ -736,7 +779,7 @@ fstab_create()
 
     local FSTAB
     FSTAB="$1/etc/fstab"
-    echo aufs / aufs defaults 0 0 > $FSTAB
+    echo overlay / overlay defaults 0 0 > $FSTAB
     echo proc /proc proc defaults 0 0 >> $FSTAB
     echo sysfs /sys sysfs defaults 0 0 >> $FSTAB
     echo devpts /dev/pts devpts gid=5,mode=620 0 0 >> $FSTAB
@@ -764,7 +807,6 @@ change_root()
     if [ ! -e dev/tty0 ]; then mknod dev/tty0 c 4 0; fi
     if [ ! -e dev/tty1 ]; then mknod dev/tty1 c 4 1; fi
     if [ ! -e dev/null ]; then mknod dev/null c 1 3; fi
-    if [ ! -e sbin/fsck.aufs ]; then ln -s /bin/true sbin/fsck.aufs; fi
 
     # find chroot and init
     if [ -x bin/chroot -o -L bin/chroot ]; then  CHROOT=bin/chroot; fi
@@ -778,7 +820,7 @@ change_root()
     if [ "$INIT" = "" ]; then fatal "init: Executable not found!"; fi
 
     mkdir -p mnt/live
-    mount -n -o remount,ro aufs .
+    mount -n -o remount,ro overlay .
     pivot_root . mnt/live
     exec $CHROOT . $INIT < dev/console > dev/console 2>&1
 }
