Merge suggestion from issue:Tomas-M/linux-live

diff --git a/livekitlib b/livekitlib
--- a/livekitlib
+++ b/livekitlib
@@ -32,14 +32,14 @@ get_lowerdirs()
 	BUND_EXT="$2"
 	MNT_OPT=""
 
-	MNT_OPT="$(find "$BUND_DIRS" -depth -type d | sed '$ d' | grep ".$BUND_EXT" | \
-	while read BUND; do echo -n "${BUND}:"; done)"
-	MNT_OPT="${MNT_OPT%?}"
-	echo "$MNT_OPT"
+	MNT_OPT="$(find "$BUND_DIRS" -maxdepth 1 -type d -name "*.${BUND_EXT}" | \
+        sort | while read BUND; do echo -n "${BUND}:"; done)"
+	    MNT_OPT="${MNT_OPT%?}"
+	    echo "$MNT_OPT"
 }
 
 # NOTE: DO NOT TOUCH THE ESCAPE CHARACTERS!
-BLUE="[1;34m"
+CYAN="[1;36m"
 YELLOW="[1;33m"
 ORANGE="[0;33m"
 GREEN="[1;32m"
@@ -80,7 +80,7 @@ debug_log()
 # $1 = text to show
 echo_fatal()
 {
-    echo "[${RED}"' fatal '"${NC}] $@" >&2
+    echo "<${RED}"'fatal'"${NC}> $*" >&2
 }
 
 # echo bold
@@ -88,36 +88,36 @@ echo_fatal()
 #
 echo_bold()
 {
-    echo "$BOLD""$@""$NC"
+    echo "$BOLD""$*""$NC"
 }
 
 # echo livekit tag
 echo_livekit()
 {
-    echo "[${BLUE}"'livekit'"${NC}] "
+    echo "<${CYAN}"'llkim'"${NC}> "
 }
 
 echo_livekit_msg()
 {
-    echo "[${BLUE}"'livekit'"${NC}] $@"
+    echo "<${CYAN}"'llkim'"${NC}> $*"
 }
 
 # echo error
 echo_err()
 {
-    echo "[${RED}"' error '"${NC}] $@" >&2
+    echo "<${RED}"'error'"${NC}> $*" >&2
 }
 
 # echo warn
 echo_warn()
 {
-    echo "[${YELLOW}"' warn! '"${NC}] $@" >&2
+    echo "<${YELLOW}"'warn!'"${NC}> $*" >&2
 }
 
 # echo signature
 echo_sign()
 {
-    echo "${BOLD}"' Linux Live Kit Improved v1.0 - '"$* ${NC}"
+    echo_bold " Live Kit Improved v1.0 (Experimental, OverlayFS) - $*" >&2
 }
 
 # log - store given text in /var/log/livedbg
@@ -136,8 +136,8 @@ echolog()
 show_debug_banner()
 {
    echo_sign "DEBUGGING MODE"
-   echo "The root shell is prepared for you!" >&2
-   echo "Type your desired commands or press Ctrl-D to continue booting." >&2
+   echo "Here's the root shell for you..." >&2
+   echo "Type your desired commands or hit Ctrl+D to continue bootup..." >&2
    echo >&2
 }
 
@@ -298,7 +298,7 @@ modprobe_overlay()
     # Prepare for error messages
     echo >>/var/log/livkekit-log
 
-    modprobe overlay 2>/var/log/livekit-log
+    modprobe overlay 2>>/var/log/livekit-log
 
     # If overlay module failed to load, panic immidiately
     if [ $? -ne 0 ]; then
